// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProgramacaoAvancada.Data;

#nullable disable

namespace SimuladorGravitacional.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112125737_CamposRenomeados_Completo")]
    partial class CamposRenomeados_Completo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProgramacaoAvancada.Models.Corpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AceleracaoX")
                        .HasColumnType("double precision")
                        .HasColumnName("aceleracao_x");

                    b.Property<double>("AceleracaoY")
                        .HasColumnType("double precision")
                        .HasColumnName("aceleracao_y");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<double>("Densidade")
                        .HasColumnType("double precision")
                        .HasColumnName("densidade");

                    b.Property<double>("Massa")
                        .HasColumnType("double precision")
                        .HasColumnName("massa");

                    b.Property<string>("Metadados")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadados");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("double precision")
                        .HasColumnName("posicao_x");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("double precision")
                        .HasColumnName("posicao_y");

                    b.Property<double>("Raio")
                        .HasColumnType("double precision")
                        .HasColumnName("raio");

                    b.Property<int>("TipoCorpo")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("tipo_corpo");

                    b.Property<int>("UniversoId")
                        .HasColumnType("integer")
                        .HasColumnName("universo_id");

                    b.Property<double>("VelocidadeX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("velocidade_x");

                    b.Property<double>("VelocidadeY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("velocidade_y");

                    b.HasKey("Id");

                    b.HasIndex("UniversoId");

                    b.ToTable("Corpos", (string)null);
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.EventoSimulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Detalhes")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhes");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("simulacao_id");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId");

                    b.ToTable("EventosSimulacao");
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuracao")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracao");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("NumeroColisoes")
                        .HasColumnType("integer")
                        .HasColumnName("numero_colisoes");

                    b.Property<int>("NumeroIteracoes")
                        .HasColumnType("integer")
                        .HasColumnName("numero_iteracoes");

                    b.Property<int>("QuantidadeCorpos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_corpos");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes", (string)null);
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Universo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaCanvas")
                        .HasColumnType("double precision")
                        .HasColumnName("altura_canvas");

                    b.Property<bool>("BordasReflexivas")
                        .HasColumnType("boolean")
                        .HasColumnName("bordas_reflexivas");

                    b.Property<bool>("ColisoesHabilitadas")
                        .HasColumnType("boolean")
                        .HasColumnName("colisoes_habilitadas");

                    b.Property<string>("Configuracao")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracao");

                    b.Property<double>("ConstanteGravitacional")
                        .HasColumnType("double precision")
                        .HasColumnName("constante_gravitacional");

                    b.Property<string>("CorFundo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor_fundo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<double>("FatorSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100000.0)
                        .HasColumnName("fator_simulacao");

                    b.Property<double>("LarguraCanvas")
                        .HasColumnType("double precision")
                        .HasColumnName("largura_canvas");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<double>("PassoTempo")
                        .HasColumnType("double precision")
                        .HasColumnName("passo_tempo");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("simulacao_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId")
                        .IsUnique();

                    b.ToTable("Universos", (string)null);
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Corpo", b =>
                {
                    b.HasOne("ProgramacaoAvancada.Models.Universo", "Universo")
                        .WithMany("Corpos")
                        .HasForeignKey("UniversoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universo");
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.EventoSimulacao", b =>
                {
                    b.HasOne("ProgramacaoAvancada.Models.Simulacao", "Simulacao")
                        .WithMany("Eventos")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Universo", b =>
                {
                    b.HasOne("ProgramacaoAvancada.Models.Simulacao", "Simulacao")
                        .WithOne("Universo")
                        .HasForeignKey("ProgramacaoAvancada.Models.Universo", "SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Simulacao", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Universo")
                        .IsRequired();
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Universo", b =>
                {
                    b.Navigation("Corpos");
                });
#pragma warning restore 612, 618
        }
    }
}
