// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProgramacaoAvancada.Data;

#nullable disable

namespace SimuladorGravitacional.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112120015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProgramacaoAvancada.Models.Corpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Densidade")
                        .HasColumnType("double precision");

                    b.Property<double>("Massa")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision");

                    b.Property<double>("Raio")
                        .HasColumnType("double precision");

                    b.Property<int>("UniversoId")
                        .HasColumnType("integer");

                    b.Property<double>("VelX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("VelY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("UniversoId");

                    b.ToTable("Corpos", (string)null);
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroColisoes")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroIteracoes")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCorpos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes", (string)null);
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Universo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CanvasHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasWidth")
                        .HasColumnType("double precision");

                    b.Property<double>("FatorSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100000.0);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId")
                        .IsUnique();

                    b.ToTable("Universos", (string)null);
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Corpo", b =>
                {
                    b.HasOne("ProgramacaoAvancada.Models.Universo", "Universo")
                        .WithMany("Corpos")
                        .HasForeignKey("UniversoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universo");
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Universo", b =>
                {
                    b.HasOne("ProgramacaoAvancada.Models.Simulacao", "Simulacao")
                        .WithOne("Universo")
                        .HasForeignKey("ProgramacaoAvancada.Models.Universo", "SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Simulacao", b =>
                {
                    b.Navigation("Universo")
                        .IsRequired();
                });

            modelBuilder.Entity("ProgramacaoAvancada.Models.Universo", b =>
                {
                    b.Navigation("Corpos");
                });
#pragma warning restore 612, 618
        }
    }
}
